-- MySQL Script generated by MySQL Workbench
-- Tue Nov 29 21:17:00 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ProjectDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ProjectDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ProjectDB` DEFAULT CHARACTER SET utf8mb4 ;
USE `ProjectDB` ;

-- -----------------------------------------------------
-- Table `ProjectDB`.`Books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjectDB`.`Books` (
  `ISBN` INT NOT NULL,
  `Title` VARCHAR(45) NULL,
  `PublicationDate` DATE NULL,
  `Price` INT(13) NULL,
  `UserReviews` INT(5) NULL,
  PRIMARY KEY (`ISBN`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectDB`.`Author`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjectDB`.`Author` (
  `AuthorID` INT NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(45) NULL,
  `LastName` VARCHAR(45) NULL,
  `Gender` VARCHAR(45) NULL,
  PRIMARY KEY (`AuthorID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectDB`.`BookCategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjectDB`.`BookCategory` (
  `CategoryCode` INT(4) NOT NULL,
  `CategoryName` VARCHAR(45) NULL,
  PRIMARY KEY (`CategoryCode`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectDB`.`Customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjectDB`.`Customers` (
  `CustomerID` INT NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(45) NULL,
  `LastName` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `Password` VARCHAR(45) NULL,
  `User_Type` VARCHAR(20) NULL DEFAULT 'user',
  PRIMARY KEY (`CustomerID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectDB`.`CustomerContactDetails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjectDB`.`CustomerContactDetails` (
  `CustomerContactID` INT NOT NULL,
  `CustomerID` INT NOT NULL,
  PRIMARY KEY (`CustomerContactID`, `CustomerID`),
  INDEX `CustomerID_idx` (`CustomerID` ASC) VISIBLE,
  CONSTRAINT `CustomerID1`
    FOREIGN KEY (`CustomerID`)
    REFERENCES `ProjectDB`.`Customers` (`CustomerID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectDB`.`AuthorContactDetails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjectDB`.`AuthorContactDetails` (
  `AuthorContactID` INT NOT NULL,
  `AuthorID` INT NOT NULL,
  PRIMARY KEY (`AuthorContactID`, `AuthorID`),
  INDEX `AuthorID_idx` (`AuthorID` ASC) VISIBLE,
  CONSTRAINT `AuthorID1`
    FOREIGN KEY (`AuthorID`)
    REFERENCES `ProjectDB`.`Author` (`AuthorID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectDB`.`Supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjectDB`.`Supplier` (
  `SupplierID` INT NOT NULL AUTO_INCREMENT,
  `SupplierName` VARCHAR(45) NULL,
  PRIMARY KEY (`SupplierID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectDB`.`SupplierRep`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjectDB`.`SupplierRep` (
  `SupplierFirstName` VARCHAR(45) NOT NULL,
  `SupplierLastName` VARCHAR(45) NOT NULL,
  `WorkNumber` INT NOT NULL,
  `CellNumber` INT NULL,
  `Email` VARCHAR(45) NULL,
  `SupplierID` INT NULL,
  PRIMARY KEY (`SupplierFirstName`, `SupplierLastName`, `WorkNumber`),
  INDEX `SupplierID_idx` (`SupplierID` ASC) VISIBLE,
  CONSTRAINT `SupplierID1`
    FOREIGN KEY (`SupplierID`)
    REFERENCES `ProjectDB`.`Supplier` (`SupplierID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectDB`.`BooksSupplied`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjectDB`.`BooksSupplied` (
  `SupplierID` INT NOT NULL,
  `ISBN` INT NOT NULL,
  PRIMARY KEY (`SupplierID`, `ISBN`),
  INDEX `ISBN_idx` (`ISBN` ASC) VISIBLE,
  CONSTRAINT `SupplierID2`
    FOREIGN KEY (`SupplierID`)
    REFERENCES `ProjectDB`.`Supplier` (`SupplierID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ISBN1`
    FOREIGN KEY (`ISBN`)
    REFERENCES `ProjectDB`.`Books` (`ISBN`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectDB`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjectDB`.`Orders` (
  `Order_ID` INT NOT NULL,
  `OrderValue` DECIMAL(19,4) NULL,
  `OrderDetails` LONGTEXT NULL,
  `CustomerID` INT NULL,
  PRIMARY KEY (`Order_ID`),
  INDEX `CustomerID_idx` (`CustomerID` ASC) VISIBLE,
  CONSTRAINT `CustomerID2`
    FOREIGN KEY (`CustomerID`)
    REFERENCES `ProjectDB`.`Customers` (`CustomerID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectDB`.`Order_Items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjectDB`.`Order_Items` (
  `Item_Number` INT NOT NULL,
  `ItemPrice` DECIMAL(19,4) NULL,
  `OrderID` INT NULL,
  `ISBN` INT NULL,
  PRIMARY KEY (`Item_Number`),
  INDEX `OrderID_idx` (`OrderID` ASC) VISIBLE,
  INDEX `ISBN_idx` (`ISBN` ASC) VISIBLE,
  CONSTRAINT `OrderID1`
    FOREIGN KEY (`OrderID`)
    REFERENCES `ProjectDB`.`Orders` (`Order_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ISBN2`
    FOREIGN KEY (`ISBN`)
    REFERENCES `ProjectDB`.`Books` (`ISBN`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectDB`.`CustomerContactAddresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjectDB`.`CustomerContactAddresses` (
  `CustomerContactID` INT NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CustomerContactID`, `Address`),
  CONSTRAINT `CustomerContactID1`
    FOREIGN KEY (`CustomerContactID`)
    REFERENCES `ProjectDB`.`CustomerContactDetails` (`CustomerContactID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectDB`.`CustomerContactEmails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjectDB`.`CustomerContactEmails` (
  `CustomerContactID` INT NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CustomerContactID`, `Email`),
  CONSTRAINT `CustomerContactID2`
    FOREIGN KEY (`CustomerContactID`)
    REFERENCES `ProjectDB`.`CustomerContactDetails` (`CustomerContactID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectDB`.`CustomerContactPhoneNumbers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjectDB`.`CustomerContactPhoneNumbers` (
  `CustomerContactID` INT NOT NULL,
  `Phone` INT(12) NOT NULL,
  PRIMARY KEY (`CustomerContactID`, `Phone`),
  CONSTRAINT `CustomerContactID3`
    FOREIGN KEY (`CustomerContactID`)
    REFERENCES `ProjectDB`.`CustomerContactDetails` (`CustomerContactID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectDB`.`AuthorContactAddresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjectDB`.`AuthorContactAddresses` (
  `AuthorContactID` INT NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`AuthorContactID`, `Address`),
  CONSTRAINT `AuthorContactID1`
    FOREIGN KEY (`AuthorContactID`)
    REFERENCES `ProjectDB`.`AuthorContactDetails` (`AuthorContactID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectDB`.`AuthorContactEmails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjectDB`.`AuthorContactEmails` (
  `AuthorContactID` INT NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`AuthorContactID`, `Email`),
  CONSTRAINT `AuthorContactID2`
    FOREIGN KEY (`AuthorContactID`)
    REFERENCES `ProjectDB`.`AuthorContactDetails` (`AuthorContactID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectDB`.`AuthorContactPhoneNumbers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjectDB`.`AuthorContactPhoneNumbers` (
  `AuthorContactID` INT NOT NULL,
  `Phone` INT(12) NOT NULL,
  PRIMARY KEY (`AuthorContactID`, `Phone`),
  CONSTRAINT `AuthorContactID3`
    FOREIGN KEY (`AuthorContactID`)
    REFERENCES `ProjectDB`.`AuthorContactDetails` (`AuthorContactID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectDB`.`WrittenBooks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjectDB`.`WrittenBooks` (
  `AuthorID` INT NOT NULL,
  `ISBN` INT(13) NOT NULL,
  PRIMARY KEY (`AuthorID`, `ISBN`),
  INDEX `ISBN_idx` (`ISBN` ASC) VISIBLE,
  CONSTRAINT `ISBN3`
    FOREIGN KEY (`ISBN`)
    REFERENCES `ProjectDB`.`Books` (`ISBN`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `AuthorID2`
    FOREIGN KEY (`AuthorID`)
    REFERENCES `ProjectDB`.`Author` (`AuthorID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectDB`.`BooksCategorized`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjectDB`.`BooksCategorized` (
  `ISBN` INT NOT NULL,
  `CategoryCode` INT(4) NOT NULL,
  PRIMARY KEY (`ISBN`, `CategoryCode`),
  INDEX `CategoryCode_idx` (`CategoryCode` ASC) VISIBLE,
  CONSTRAINT `ISBN4`
    FOREIGN KEY (`ISBN`)
    REFERENCES `ProjectDB`.`Books` (`ISBN`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `CategoryCode1`
    FOREIGN KEY (`CategoryCode`)
    REFERENCES `ProjectDB`.`BookCategory` (`CategoryCode`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
